config/routes.rb
Rails.application.routes.draw do
  root 'prototypes/popular#index'

  devise_for :users
  resources :users, only: [:show, :edit, :update]
  resources :prototypes do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  scope module: :prototypes do
    resources :popular, only: :index
    resources :newest, only: :index
  end
  resources :tags, only: [:index, :show], param: :tag_name
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :prototype

  validates :article, presence: true
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user  
  belongs_to :prototype, counter_cache: :likes_count
end

app/models/prototype.rb
class Prototype < ActiveRecord::Base
  belongs_to :user
  has_many   :likes, dependent: :destroy  
  has_many   :comments, dependent: :delete_all
  has_many   :prototype_images, dependent: :delete_all
  accepts_nested_attributes_for :prototype_images, reject_if: lambda { |attributes| attributes['content'].blank? }, allow_destroy: true

  validates :title, 
  :catch_copy, 
  :concept, 
  presence: true

  def like_by?(user)
   likes.find_by(user_id: user)
  end

  MAXMUN_IMAGE_NUM = 3
  def set_sub_thumbnails
    sub_images = prototype_images.sub
    MAXMUN_IMAGE_NUM.times { |i| sub_images[i] ||= prototype_images.build(status: "sub") }
      sub_images
  end

  acts_as_taggable
  
end

app/models/prototype_image.rb
class PrototypeImage < ActiveRecord::Base
	belongs_to :user
	belongs_to :prototype

	enum status: {main: 1, sub: 2}

	validates (:content || :main), presence: true

	mount_uploader :content, PrototypeContentUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :prototypes
  has_many :prototype_images
  has_many :likes
  has_many :comments

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # def after_sign_out_path_for(resource)
  #   'prototypes#index'
  # end
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:name, :profile, :works, :member_of, :image]
    devise_parameter_sanitizer.for(:account_update) << [:name, :profile, :works, :member_of, :image]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_prototype, only: :create

  def create
    @prototype.comments.create(comment_params)
    @comments = Comment.where(prototype_id: params[:prototype_id])
  end

  private
  def comment_params
    params.require(:comment).permit(:article).merge(user_id: current_user.id)
  end

  def set_prototype
    @prototype = Prototype.find(params[:prototype_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.create(user_id: current_user.id, prototype_id: params[:prototype_id])
    @prototype = Prototype.find(params[:prototype_id])
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, prototype_id: params[:prototype_id])
    like.destroy
    @prototype = Prototype.find(params[:prototype_id])
  end
end

app/controllers/prototypes/newest_controller.rb
class Prototypes::NewestController < ApplicationController
  def index
    @prototypes = Prototype.includes(:users).order("created_at DESC")
  end
end

app/controllers/prototypes/popular_controller.rb
class Prototypes::PopularController < ApplicationController
  def index
    @prototypes = Prototype.includes(:users).order(likes_count: :desc)
  end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  before_action :set_prototype, only: [:show, :destroy, :edit, :update]

  def index
    @prototypes = Prototype.all.includes(:prototype_images)
    @tags = ActsAsTaggableOn::Tag.all
  end

  def show
    @comment = Comment.new
    @comments = @prototype.comments.includes(:user)
    @like = @prototype.likes.find_by(user_id: current_user.id)
    @sub_images = @prototype.prototype_images.sub
  end

  def new
    @prototype = Prototype.new
    @prototype.prototype_images.build
  end

  def create
    @prototype = Prototype.new(prototype_params)
    binding.pry
    if @prototype.save
      redirect_to prototypes_path(@prototype), notice: "新しいプロトタイプを登録しました"
    else
      render 'new'
    end
  end

  def destroy
    if @prototype.user_id == current_user.id
      @prototype.destroy
      redirect_to :root, notice: "プロトタイプを削除しました"
    end
  end

  def edit
    @main_image = @prototype.prototype_images.main.first
    @sub_images = @prototype.set_sub_thumbnails
  end

  def update
    if  @prototype.update(prototype_params)
      redirect_to :root, notice: "プロトタイプを更新しました"
    else
      render 'edit'
    end
  end

  private
  def prototype_params
    params.require(:prototype).permit(:title, :catch_copy, :concept, prototype_images_attributes: [:id, :content, :status, :_destroy]).merge(user_id: current_user.id, tag_list: params[:prototype][:tag_list])
  end

  def set_prototype
  	@prototype = Prototype.find(params[:id])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.most_used.where("name not ?", nil)
  end

  def show
    @tag =  ActsAsTaggableOn::Tag.where(params[:tag_name])
    @prototypes = Prototype.tagged_with(@tag.name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :update]
  before_action :authenticate_user!, only: :edit

  def show
    @prototypes = @user.prototypes
  end

  def edit
  end

  def update
    if current_user.update(user_params)
       redirect_to user_path, notice: "ユーザー情報を更新しました"
    else
       render 'edit'
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :description, :image, :email, :profile, :member_of, :works)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.haml
.media
  .media-left
    = image_tag comment.user.image, class: "media-object", alt: "64x64", "data-holder-rendered": "true", "data-src": "holder.js/64x64", style: "width: 64px; height: 64px;"
  .media-body
    .media-heading
      = comment.user.name
    %p
      = comment.article

app/views/comments/create.js.erb
$('#comment_field').val('');
$('#comment_list').html(
  '<%= j(render partial: 'comments/comment', collection: @comments) %>'
);
$('#comment_count').html(
  '(<%= @prototype.comments.count %>)'
);

app/views/layouts/_footer.html.haml
.container
  %footer
    %p 
    &copy; PROTO SPACE 2015.

app/views/layouts/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand(href="/")
      = image_tag("logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "36px")
    .navbar-collapse.collapse.navbar-responsive-collapse
      - if user_signed_in?
        //login
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded": "false", "data-toggle": "dropdown", href: "#", role: "button"}
              = current_user.name
              %span.caret
            %ul.dropdown-menu{role: "menu"}
              %li
                = link_to "My page", user_path(current_user), method: "get"
              %li
                = link_to "Profile Edit", edit_user_path(current_user), method: "get" 
              %li
                = link_to "Logout", destroy_user_session_path, method: "delete"
          %li
            .btn.btn-primary.navbar-btn
              = link_to "New Proto", new_prototype_path, method: "get"
      -else
        //not login
        %ul.nav.navbar-nav.navbar-right
          %li
            .btn.btn-primary.navbar-btn
              = link_to "Get Started", new_user_session_path, method: "get"
                

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=US-ASCII", "http-equiv" => "Content-Type"}/
    %title Protospace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render "layouts/header"
    - flash.each do |key, value|
      - key = "info" if key == "notice"
      - key = "danger"  if key == "alert"
      = content_tag :div, value, class: "alert alert-#{key}"
    = yield
    = render "layouts/footer"

app/views/likes/_like.html.haml
.likes-box
- if user_signed_in?
  - if @prototype.like_by?(current_user.id)
    = button_to prototype_like_path(prototype, like), method: :delete, id: "like-button", class: "btn btn-default decrement-button", remote: true do
      = image_tag("icon_red_heart.svg")
      Like
      %span.num#like-sum #{prototype.likes_count}
  - else
    = button_to prototype_likes_path(prototype), id: "like-button", class: "btn btn-default decrement-button", remote: true do
      = image_tag("icon_heart.svg")
      Like
      %span.num#like-sum #{prototype.likes_count}
- else
  %button.btn.btn-default
    = image_tag("icon_heart.svg")
    Like
    %span.num#like-sum #{prototype.likes_count}

app/views/likes/create.js.erb
$("#like-button").html("<%= j(render partial: 'like', locals: { like: @like, prototype: @prototype }) %>");

app/views/likes/destroy.js.erb
$("#like-button").html("<%= j(render partial: 'like', locals: { prototype: @prototype }) %>");

app/views/prototypes/_prototype.html.haml
.col-sm-4.col-md-3.proto-content
  - if user_signed_in? && current_user.id == prototype.user_id
    //login
    .dropdown.drop_menu_location
      %button.btn.btn-default-action.dropdown-toggle{"aria-expanded": "false", "data-toggle": "dropdown",id: "dropdownMenu", type: "button"}Action
      %ul.dropdown-menu{"aria-labelledby": "dropdownMenu1"}
        %li
          = link_to "Delete", prototype_path(prototype), method: "delete"
        %li
          = link_to "Edit", edit_prototype_path(prototype), method: "get" 
  .thumbnail
    = link_to image_tag(prototype.prototype_images.main[0].content.url), prototype_path(prototype)
    .caption
      %h3
      = prototype.title
      .proto-meta
        .proto-user
          = prototype.user.name
        .proto-posted
          = prototype.created_at.strftime("%m月%d日")
    %ul.proto-tag-list.list-inline
    - @tags.each do |tag|
      %li
        %a.btn.btn-default
        = tag

app/views/prototypes/edit.html.haml
.container.proto-new
  = form_for @prototype do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          = f.text_field :title, placeholder: "@prototype.title"
      .row
        .col-md-12
          = f.fields_for :prototype_images, @main_image do |prototype_images_form|
            .cover-image-upload
              = prototype_images_form.file_field :content
              = prototype_images_form.hidden_field :status, value: "main"
          %ul.proto-sub-list.list-group
            %li.list-group-item.col-md-4
              = f.fields_for :prototype_images, @sub_images do |prototype_images_form|
                .image-upload
                  = prototype_images_form.file_field :content
                  = prototype_images_form.hidden_field :status, value: "sub"

      .row.proto-description
        .col-md-12
          = f.text_field :catch_copy, placeholder: "@prototype.catch_copy"
        .col-md-12
          = f.text_field :concept, cols: "30", rows: "4", placeholder: "@prototype.concept"
        .col-md-12
          %h4 Tag List
          .row
            .col-md-3
              %input{type: "text", placeholder: "Web Design"}/
            .col-md-3
              %input{type: "text", placeholder: "UI"}/
            .col-md-3
              %input{type: "text", placeholder: "Application"}/
      .row.text-center.proto-btn
        =f.submit "Publish", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")
.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.active{role: "presentation"}
          = link_to "Popular PROTO", popular_index_path, method: "get"
        %li{role: "presentation"}
          = link_to "Newest PROTO", newest_index_path, method: "get"
      %button{type: "button", class: "btn btn-default col-lg-1"} View Tags

.container.proto-list
  .row
    = render @prototypes
.text-center
  %ul.pagination
    %li.disabled
      %a{"aria-label" => "Previous", href: "#"}
        %span{"aria-hidden" => "true"} «
    %li.active
      %a{href: "#"}
        1
        %span.sr-only (current)
    %li
      %a{href: "#"} 2
    %li
      %a{href: "#"} 3
    %li
      %a{href: "#"} 4
    %li
      %a{href: "#"} 5
    %li
      %a{"aria-label": "Next", href: "#"}
        %span{"aria-hidden": "true"} »

app/views/prototypes/new.html.haml
.container.proto-new
  = form_for @prototype do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          = f.text_field :title, type: "text", placeholder: "Title"
      .row
      = f.fields_for :prototype_images do |prototype_images_form|
        .col-md-12
          .cover-image-upload
            = prototype_images_form.file_field :content
            = prototype_images_form.hidden_field :status, value: "main"
        .col-md-12
          %ul.proto-sub-list.list-group
            %li.list-group-item.col-md-4
              .image-upload
                = f.fields_for :prototype_images do |prototype_images_form|
                  = prototype_images_form.file_field :content
                  = prototype_images_form.hidden_field :status, value: "sub"
            %li.list-group-item.col-md-4
              .image-upload
                = f.fields_for :prototype_images do |prototype_images_form|
                  = prototype_images_form.file_field :content
                  = prototype_images_form.hidden_field :status, value: "sub"
            %li.list-group-item.col-md-4
              .image-upload-plus
                %span +
                = f.fields_for :prototype_images do |prototype_images_form|
                  = prototype_images_form.file_field :content
                  = prototype_images_form.hidden_field :status, value: "sub"
      .row.proto-description
        .col-md-12
          = f.text_field :catch_copy, type: "text", placeholder: "Catch Copy"
        .col-md-12
          = f.text_field :concept, cols: "30", rows: "4", placeholder: "Concept"
        .col-md-12
          %h4 Tag List
          .row
            .col-md-3
              = text_field_tag 'prototype[tag_list][]','', placeholder: "Web Design"
            .col-md-3
              = text_field_tag 'prototype[tag_list][]','', placeholder: "UI"
            .col-md-3
              = text_field_tag 'prototype[tag_list][]','', placeholder: "Application"
      .row.text-center.proto-btn
        =f.submit "Publish", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/newest/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")
.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li{role: "presentation"}
          = link_to "Popular PROTO", popular_index_path, method: "get"
        %li.active{role: "presentation"}
          = link_to "Newest PROTO", newest_index_path, method: "get"
      %button{type: "button", class: "btn btn-default col-lg-1"} View Tags

.container.proto-list
  .row
    = render partial: 'prototypes/prototype', collection: @prototypes
.text-center
  %ul.pagination
    %li.disabled
      %a{"aria-label" => "Previous", href: "#"}
        %span{"aria-hidden" => "true"} «
    %li.active
      %a{href: "#"}
        1
        %span.sr-only (current)
    %li
      %a{href: "#"} 2
    %li
      %a{href: "#"} 3
    %li
      %a{href: "#"} 4
    %li
      %a{href: "#"} 5
    %li
      %a{"aria-label": "Next", href: "#"}
        %span{"aria-hidden": "true"} »

app/views/prototypes/popular/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")
.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.active{role: "presentation"}
          = link_to "Popular PROTO", popular_index_path, method: "get"
        %li{role: "presentation"}
          = link_to "Newest PROTO", newest_index_path, method: "get"
      %button{type: "button", class: "btn btn-default col-lg-1"} View Tags

.container.proto-list
  .row
    = render partial: 'prototypes/prototype', collection: @prototypes
.text-center
  %ul.pagination
    %li.disabled
      %a{"aria-label" => "Previous", href: "#"}
        %span{"aria-hidden" => "true"} «
    %li.active
      %a{href: "#"}
        1
        %span.sr-only (current)
    %li
      %a{href: "#"} 2
    %li
      %a{href: "#"} 3
    %li
      %a{href: "#"} 4
    %li
      %a{href: "#"} 5
    %li
      %a{"aria-label": "Next", href: "#"}
        %span{"aria-hidden": "true"} »

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          = image_tag current_user.image, alt: "64x64", "data-holder-rendered": "true", "data-src": "holder.js/64x64", style: "width: 64px; height: 64px;"
        .media-body
          %h4#top-aligned-media.media-heading
            Top aligned media
          .proto-user
            = link_to current_user.name, user_path(current_user)
            %span.degree 
            = current_user.profile
            = current_user.works
    .col-md-6.text-right#like-button
      = render partial: "likes/like", locals: { like: @like, prototype: @prototype }
          
  .row
    .col-md-9
      = image_tag(@prototype.prototype_images.main[0].content, class: 'img-responsive')
    .col-md-3
      - @sub_images.each do |sub_image|
        %ul.proto-sub-list.list-group
          %li.list-group-item
            = image_tag(sub_image.content, class: 'img-responsive')
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p 
      = @prototype.catch_copy
    .col-md-6
      %h4 Concept
      %p 
      = @prototype.concept
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        %li

  %h4.col-md-12
    Comments
    %span.num#comment_count
      (#{@prototype.comments.count})

    .row.proto-comments
      #comment_list
        = render @comments

      .col-md-8
        .form-inline{role: "form"}
          %h4 Write a comment
          .row
            %div.form-group.col-md-10
              = form_for [@prototype, @comment], remote: true do |f|
                = f.text_area :article, id: "comment_field", placeholder: "Your comments"
                = f.hidden_field :user_id, value: current_user.id
                = f.submit :comment, class: "btn btn-primary"

app/views/users/edit.html.haml
.container.user-new 
  = form_for current_user do |f| 
    - if current_user.errors.any?
      #error_explanation
        %h2
          = current_user.errors.count
          件のエラーがあります。
        %ul
          - current_user.errors.full_messages.each do |msg|
            %li= msg
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h2 Edit Profile
          .user-name_image.row
            .user-name.col-md-10
              = f.text_field :name, type: "text", placeholder: "Username"
            .user-image.col-md-2
              %button.btn.btn-primary Change image
              = f.file_field :image, type: "file"
              = f.hidden_field :image_cache
          = f.text_field :email, type: "email", placeholder: "E-Mail", class: "user-email"
          = f.password_field :password, type: "password", placeholder: "password"
        .col-md-12
          %h4 Member of
          .user-user-member.row
            .user-name.col-md-12
              =f.text_field :member_of, type: "text", placeholder: "Member"
          %h4 Profile
          .user-user-profile.row
            .user-name.col-md-12
              = f.text_field :profile, cols: "30", rows: "4", placeholder: "Profile"
          %h4 Works
          .user-name_image.row
            .user-name.col-md-12
              = f.text_field :works, cols: "30", rows: "4", placeholder: "Works"
      .row.text-center.user-btn
        = f.submit "Save", class: "btn btn-lg btn-primary btn-block"

app/views/users/show.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        = image_tag @user.image.url, alt: "64x64", "data-holder-rendered": "true", "data-src": "holder.js/64x64", style: "width: 64px; height: 64px;"
      .media-body
        %h4#top-aligned-media.media-heading
          Top aligned media
          %span.label.label-default.project-number
            29
            %i Projects
        .proto-user
          %span.degree
          = @user.member_of
        .row
          .col-md-6
            %h4 Profile
            %p
            = @user.profile
          .col-md-6
            %h4 Works
            %p
            = @user.works
.container.proto-list
  .row
  - @prototypes.each do |prototype|
    .col-sm-4.col-md-3.proto-content
      .dropdown.drop_menu_location
        %button.btn.btn-default-action.dropdown-toggle{"aria-expanded": "false", "data-toggle": "dropdown",id: "dropdownMenu", type: "button"}Action
        %ul.dropdown-menu{"aria-labelledby": "dropdownMenu1"}
          %li
            = link_to "Delete", prototype_path(prototype), method: "delete"
          %li
            = link_to "Edit", edit_prototype_path(prototype), method: "get" 
      .thumbnail
        %a{href: ""}
          = link_to image_tag(prototype.prototype_images.main[0].content, class: 'img-responsive'), prototype_path(prototype)
          .caption
            %h3
            = link_to "#{prototype.title}", prototype_path(prototype.id)
            .proto-meta
              .proto-date
                = prototype.created_at.strftime("%m月%d日")
            %ul.proto-tag-list.list-inline
              %li
                %a{href: "#", class: "btn btn-default"} iPad
              %li
                %a{href: "#", class: "btn btn-default"} wireframe

.text-center
  %ul.pagination
    %li.disabled
      %a{"aria-label": "Previous", href: "#"}
        %span{"aria-hidden": "true"} «
    %li.active
      %a{href: "#"}
        1
        %span.sr-only (current)
    %li
      %a{href: "#"} 2
    %li
      %a{href: "#"} 3
    %li
      %a{href: "#"} 4
    %li
      %a{href: "#"} 5
    %li
      %a{"aria-label": "Next", href: "#"}
        %span{"aria-hidden": "true"} »